Merging feature-branch to master
Kyle-Law/newsweek-clone pull request #1
Opened 2020-01-30 10:25 UTC by Kyle-Law

It is a replica of the news site [newsweek.com](https://www.newsweek.com/). Bootstrap classes are used throughout the project. Any ads, icons, and interactive elements are ignored as specified in [The Odin project](https://www.theodinproject.com/courses/html5-and-css3/lessons/using-bootstrap)
This project is done solely by @Kyle-Law .

This is my first time using Bootstrap. Reviews with detailed suggestions are highly appreciated :)

2020-01-30 11:24 UTC, rOluochKe requested changes
Hello @Kyle-Law 
### You have done a good job so far, however, there are a number of issues you need to fix before approval
- Your project layout is broken, check this image. First, fix your layout, header, content, sidebar
![layout](https://user-images.githubusercontent.com/8114528/73444736-41567180-436a-11ea-88ae-bc92f1db1b40.PNG)
- To work with responsive images, it is advised to always use` width = 100%` with this it will adjust to every device, your images are squeezed
- Work on your footer, check the origin design
- Also, put more work on responsiveness, make sure it responds well to different devices, mobile, tablet, and desktop. Currently is breaking
![responsive design](https://user-images.githubusercontent.com/8114528/73445286-65ff1900-436b-11ea-9935-e637aea31bec.PNG)
- Avoid inline css in your html file
![css](https://user-images.githubusercontent.com/8114528/73445445-bb3b2a80-436b-11ea-856a-daf119e54023.PNG)
- In your css file, don't use the key `!important`

### Once you make all these changes, you can resubmit for another review. I wish you all the best.
- If you are facing any problem with the project, reach out to me on [Raymond](@rOluochKe)

2020-01-30 15:00 UTC, Kyle-Law commented
Thank @rOluochKe for reviewing my project! Your suggestions have been applied as listed below:

- Layout smoothened by enclosing `.card` with `.col-`
- inline CSS removed
- `!important` remove
- Footer section fixed by enclosing them with `.row`

Looking forward to another review by TSEs! This is my first time using bootstrap, detailed suggestions are highly appreciated :)

2020-01-30 18:03 UTC, mosesogwo requested changes
**Hi @Kyle-Law :clap:, great job so far. We have a few miles to go :smile:**

1. Your navbar is not responsive. Compare the appearance on medium and small screens with the original.

2, On medium screen, images in the **"In the magazine"** section are squeezed. Try saving the images directly from the original page in the webp format that they have instead of jpg.

3. On medium screen, **"Editor's Pick"** section should be aligned in two-columns per row.

4. Let's have some padding at the top of the footer section as it is in the original page.
![image](https://user-images.githubusercontent.com/46611870/73476315-45968500-4392-11ea-98fb-de77407802eb.png)

5. The footer is not responsive to small screens. Compare yours with the original.
![image](https://user-images.githubusercontent.com/46611870/73476398-6bbc2500-4392-11ea-9d02-eb83fdd98517.png)

6. Wrap your footer section in `<footer>` tags.

7. Use bootstrap classes for your flex styling. You can look at this doc https://mdbootstrap.com/docs/jquery/utilities/flexbox/

_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack - Moses Ogwo**

**Happy Coding:smile:**

**Status: Changes requested**.

2020-01-31 02:13 UTC, Kyle-Law commented
Thank @mosesogwo  for reviewing my project! Your suggestions have been applied as listed below: 
- navbar responsiveness fixed.
- In the magazine images responsiveness fixed with media queries. (Tried webp format)
- Editor's Pick section aligned into 2 columns on medium screens.
- Footer padding-top added.
- Footer responsiveness fixed.
- Wrapped footer with `<footer>` tag.

Others:
- Header layout and breakpoints refined.
- Navbar breakpoint refined.
- Top search bar effects on focus added. 

Looking forward to another review by TSEs :)

2020-01-31 02:17 UTC, Kyle-Law commented
Thank @mosesogwo  for reviewing my project! Your suggestions have been applied as listed below: 
- navbar responsiveness fixed.
- In the magazine images responsiveness fixed with media queries. (Tried webp format)
- Editor's Pick section aligned into 2 columns on medium screens using `col-md-6`
- Footer padding-top added.
- Footer responsiveness fixed by aligning them into rows on smaller screens.
- Wrapped footer with `<footer>` tag.

Others:
- Header layout and breakpoints refined.
- Navbar breakpoint refined.
- Top search bar effects on focus added. 

Looking forward to another review by TSEs :)

2020-01-31 04:47 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Quemé P. (TSE)

### Hello @Kyle-Law :handshake: 

### This is a great effort :medal_sports: but your page still needs work :building_construction: 

**navbar**

- [x] Add the gray separator between buttons (perhaps a border-right) of the navbar

- Yours

![image](https://user-images.githubusercontent.com/52209067/73512803-a03ed980-43b0-11ea-8444-7d13af2a1f37.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/73512843-ccf2f100-43b0-11ea-9dcd-74bebf6b4ecc.png)

**missing sections**

- [x] Your page is missing the **U.S**, **World**, **Business**, **Tech & Science**, **Culture** and **Sports** sections between the **FEATURED SLIDESHOWS** and **SUBSCRIBE** sections, make sure you add them before requesting for  a code review again.

**NEWSLETTER**

- [x]  it should have a red title with all caps

- Yours
![image](https://user-images.githubusercontent.com/52209067/73511992-79cb6f00-43ad-11ea-97ad-107091962e56.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/73512012-95367a00-43ad-11ea-9e5b-e64063ff48ff.png)


**navbar(small screen)**

- [x] the **Newsweek**, **Sign In**, **Subscribe** and **Hamburger menu** have to fit all in it and they have to occupy 100% of the page width

- Yours

![image](https://user-images.githubusercontent.com/52209067/73510833-2a833f80-43a9-11ea-92a0-53a29cc667f8.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/73510491-e2afe880-43a7-11ea-97fd-f222ee4b3058.png)

**small screen**

- [x] The **TOP STORY** is the first article to show in the page please use the Bootstrap classes **.flex-row-reverse** or **.flex-column-reverse** to achieve this behavior (find examples [here](https://getbootstrap.com/docs/4.4/utilities/flex/#direction))

- Yours

![image](https://user-images.githubusercontent.com/52209067/73510763-f4de5680-43a8-11ea-8ca6-ae79d5d618d0.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/73510793-09225380-43a9-11ea-86a2-7dada1057750.png)

- [x]  The MORE STORIES -> CULTURE & TRAVEL -> FEATURE STORIES -> OPINION -> LATEST NEWS -> NEWSWEEK ISSUE -> IN THE MAGAZINE -> EDITOR'S PICK -> FEATURED SLIDESHOWS -> U.S -> World -> Business -> Tech & Science -> Culture -> Sports -> SUBSCRIBE -> NEWSLETTER   Sections should come in that order when scrolling down the page

- [x] All articles should  occupy at least  90% of the page width

**medium screen (breakpoint-md: 768px)**

- [x] All sections should  occupy at least  90% of the page width

- Yours (it happens in all sections not just the one in the image)

![image](https://user-images.githubusercontent.com/52209067/73512162-36bdcb80-43ae-11ea-96fc-2ea03e8c675e.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/73512201-5b19a800-43ae-11ea-9511-476112b8cf84.png)

**large screen (breakpoint-lg: 992px)**

- [x] All sections should  occupy at least  95% of the page width

- [x] **FEATURE STORIES**, **TOP STORY** and **OPINION** sections are displayed in the first row of the page

- Yours 

![image](https://user-images.githubusercontent.com/52209067/73512365-f579eb80-43ae-11ea-890c-e67cbb47c1bd.png)

- Original
![image](https://user-images.githubusercontent.com/52209067/73512390-0cb8d900-43af-11ea-9ded-98a110d29eba.png)

- [x] **EDITOR'S PICK** should have 4 articles per row instead of 2

- Yours

![image](https://user-images.githubusercontent.com/52209067/73512522-8650c700-43af-11ea-937c-728b570ee5c6.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/73512545-9a94c400-43af-11ea-8779-6321396a0909.png)

- [x] **SUBSCRIBE** and **NEWSLETTER** should be in the same row

- Yours

![image](https://user-images.githubusercontent.com/52209067/73512608-e8a9c780-43af-11ea-889b-897a4bed865d.png)

- Original 

![image](https://user-images.githubusercontent.com/52209067/73512640-feb78800-43af-11ea-8377-45f32900438f.png)

**extra-large screen (breakpoint-xl: 1200px)**

- [x] All sections should  occupy at least  95% of the page width

**Bootstrap Usage**

- [ ] This project is all about using Bootstrap that is why your CSS file shouldn't contain selectors that can be found in [Bootstrap](https://getbootstrap.com/docs/4.4/getting-started/introduction/), I have commented your code in the lines where selectors should be remove or modified and add the respective Bootstrap classes in your HTML file.

### That is it! :raised_hands: Please :pray:  make the changes and submit back for a code review when you are done :rocket: 

Happy Coding! :woman_technologist:  

STATUS OF THE PROJECT: REQUESTED CHANGES :vertical_traffic_light:

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  display: flex;
Don't use **display: flex;** CSS selector, bootstrap has a **.d-flex** class already use it directly in your CSS file instead

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  font-weight: 600;
Do not use font-weight selector bootstrap has its own [classes for font-weight](https://getbootstrap.com/docs/4.4/utilities/text/#font-weight-and-italics) use them directly in the HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  font-weight: 700;
Do not use font-weight selector bootstrap has its own [classes for font-weight](https://getbootstrap.com/docs/4.4/utilities/text/#font-weight-and-italics) use them directly in the HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  font-weight: 800;
Do not use font-weight selector bootstrap has its own [classes for font-weight](https://getbootstrap.com/docs/4.4/utilities/text/#font-weight-and-italics) use them directly in the HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  font-weight: 700;
Do not use font-weight selector bootstrap has its own [classes for font-weight](https://getbootstrap.com/docs/4.4/utilities/text/#font-weight-and-italics) use them directly in the HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  font-weight: 600;
Do not use font-weight selector bootstrap has its own [classes for font-weight](https://getbootstrap.com/docs/4.4/utilities/text/#font-weight-and-italics) use them directly in the HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  font-weight: 600;
Do not use font-weight selector bootstrap has its own [classes for font-weight](https://getbootstrap.com/docs/4.4/utilities/text/#font-weight-and-italics) use them directly in the HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  font-weight: 600;
Do not use font-weight selector bootstrap has its own [classes for font-weight](https://getbootstrap.com/docs/4.4/utilities/text/#font-weight-and-italics) use them directly in the HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  font-weight: 600;
Do not use font-weight selector bootstrap has its own [classes for font-weight](https://getbootstrap.com/docs/4.4/utilities/text/#font-weight-and-italics) use them directly in the HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  font-weight: 600;
Do not use font-weight selector bootstrap has its own [classes for font-weight](https://getbootstrap.com/docs/4.4/utilities/text/#font-weight-and-italics) use them directly in the HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  font-weight: 700;
Do not use font-weight selector bootstrap has its own [classes for font-weight](https://getbootstrap.com/docs/4.4/utilities/text/#font-weight-and-italics) use them directly in the HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  font-weight: 600;
Do not use font-weight selector bootstrap has its own [classes for font-weight](https://getbootstrap.com/docs/4.4/utilities/text/#font-weight-and-italics) use them directly in the HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  font-weight: 700;
Do not use font-weight selector bootstrap has its own [classes for font-weight](https://getbootstrap.com/docs/4.4/utilities/text/#font-weight-and-italics) use them directly in the HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  font-weight: 600;
Do not use font-weight selector bootstrap has its own [classes for font-weight](https://getbootstrap.com/docs/4.4/utilities/text/#font-weight-and-italics) use them directly in the HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  font-weight: 700;
Do not use font-weight selector bootstrap has its own [classes for font-weight](https://getbootstrap.com/docs/4.4/utilities/text/#font-weight-and-italics) use them directly in the HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  padding: 0;
Don't use selector for margin and padding that are equal to zero, you can use [Bootstrap classes for spacing ](https://getbootstrap.com/docs/4.4/utilities/spacing/)and call them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  margin: 0;
Don't use selector for margin and padding that are equal to zero, you can use [Bootstrap classes for spacing ](https://getbootstrap.com/docs/4.4/utilities/spacing/)and call them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  margin: 0;
Don't use selector for margin and padding that are equal to zero, you can use [Bootstrap classes for spacing ](https://getbootstrap.com/docs/4.4/utilities/spacing/)and call them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  margin: 0;
Don't use selector for margin and padding that are equal to zero, you can use [Bootstrap classes for spacing ](https://getbootstrap.com/docs/4.4/utilities/spacing/)and call them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  margin: 0;
Don't use selector for margin and padding that are equal to zero, you can use [Bootstrap classes for spacing ](https://getbootstrap.com/docs/4.4/utilities/spacing/)and call them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  margin: 0 10px;
Don't use selector for margin and padding that are equal to zero, you can use [Bootstrap classes for spacing ](https://getbootstrap.com/docs/4.4/utilities/spacing/)and call them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  margin: 0 auto;
Don't use selector for margin and padding that are equal to zero, you can use [Bootstrap classes for spacing ](https://getbootstrap.com/docs/4.4/utilities/spacing/)and call them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  text-align: center;
Don't use selectors for text-align [Bootstrap has classes for text-alignment](https://getbootstrap.com/docs/4.4/utilities/text/#text-alignment) use them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  text-align: center;
Don't use selectors for text-align [Bootstrap has classes for text-alignment ](https://getbootstrap.com/docs/4.4/utilities/text/#text-alignment)use them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  text-align: center;
Don't use selectors for text-align [Bootstrap has classes for text-alignment ](https://getbootstrap.com/docs/4.4/utilities/text/#text-alignment)use them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  text-align: center;
Don't use selectors for text-align [Bootstrap has classes for text-alignment ](https://getbootstrap.com/docs/4.4/utilities/text/#text-alignment)use them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  padding: 0 40px;
Don't use selector for margin and padding that are equal to zero, you can use [Bootstrap classes for spacing ](https://getbootstrap.com/docs/4.4/utilities/spacing/)and call them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  padding: 0;
Don't use selector for margin and padding that are equal to zero, you can use [Bootstrap classes for spacing ](https://getbootstrap.com/docs/4.4/utilities/spacing/)and call them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  padding: 0;
Don't use selector for margin and padding that are equal to zero, you can use [Bootstrap classes for spacing ](https://getbootstrap.com/docs/4.4/utilities/spacing/)and call them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  padding: 0;
Don't use selector for margin and padding that are equal to zero, you can use [Bootstrap classes for spacing ](https://getbootstrap.com/docs/4.4/utilities/spacing/)and call them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  padding: 0 15px;
Don't use selector for margin and padding that are equal to zero, you can use [Bootstrap classes for spacing ](https://getbootstrap.com/docs/4.4/utilities/spacing/)and call them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  display: block;
Do not use selectors for display, [Bootstrap has classes for display](https://getbootstrap.com/docs/4.4/utilities/display/), use them directly in your HTML file.

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  display: block;
Do not use selectors for display, [Bootstrap has classes for display](https://getbootstrap.com/docs/4.4/utilities/display/), use them directly in your HTML file.

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  display: flex;
Do not use selectors for display, [Bootstrap has classes for display](https://getbootstrap.com/docs/4.4/utilities/display/), use them directly in your HTML file.

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  display: none;
Do not use selectors for display, [Bootstrap has classes for display](https://getbootstrap.com/docs/4.4/utilities/display/), use them directly in your HTML file.

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  display: block;
Do not use selectors for display, [Bootstrap has classes for display](https://getbootstrap.com/docs/4.4/utilities/display/), use them directly in your HTML file.

2020-01-31 04:47 UTC, euqueme commented on main.css
> +    display: block;
Do not use selectors for display, [Bootstrap has classes for display](https://getbootstrap.com/docs/4.4/utilities/display/), use them directly in your HTML file.

2020-01-31 04:47 UTC, euqueme commented on main.css
> +    display: none;
Do not use selectors for display, [Bootstrap has classes for display](https://getbootstrap.com/docs/4.4/utilities/display/), use them directly in your HTML file.

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  display: block;
Do not use selectors for display, [Bootstrap has classes for display](https://getbootstrap.com/docs/4.4/utilities/display/), use them directly in your HTML file.

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  display: none;
Do not use selectors for display, [Bootstrap has classes for display](https://getbootstrap.com/docs/4.4/utilities/display/), use them directly in your HTML file.

2020-01-31 04:47 UTC, euqueme commented on main.css
> +    display: none;
Do not use selectors for display, [Bootstrap has classes for display](https://getbootstrap.com/docs/4.4/utilities/display/), use them directly in your HTML file.

2020-01-31 04:47 UTC, euqueme commented on main.css
> +    display: block;
Do not use selectors for display, [Bootstrap has classes for display](https://getbootstrap.com/docs/4.4/utilities/display/), use them directly in your HTML file.

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  align-items: flex-end;
Don't use the align-items selector, [Bootstrap has classes for align-items](https://getbootstrap.com/docs/4.4/utilities/flex/#align-items), use them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  align-items: center;
Don't use the align-items selector, [Bootstrap has classes for align-items](https://getbootstrap.com/docs/4.4/utilities/flex/#align-items), use them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  align-items: center;
Don't use the align-items selector, [Bootstrap has classes for align-items](https://getbootstrap.com/docs/4.4/utilities/flex/#align-items), use them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  align-items: baseline;
Don't use the align-items selector, [Bootstrap has classes for align-items](https://getbootstrap.com/docs/4.4/utilities/flex/#align-items), use them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  align-items: center;
Don't use the align-items selector, [Bootstrap has classes for align-items](https://getbootstrap.com/docs/4.4/utilities/flex/#align-items), use them directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  text-decoration: none;
Don't use the text-decoration selector [Bootstrap has a class for text-decoration](https://getbootstrap.com/docs/4.4/utilities/text/#text-decoration) use it directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  text-decoration: none;
Don't use the text-decoration selector [Bootstrap has a class for text-decoration](https://getbootstrap.com/docs/4.4/utilities/text/#text-decoration) use it directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  text-decoration: none;
Don't use the text-decoration selector [Bootstrap has a class for text-decoration](https://getbootstrap.com/docs/4.4/utilities/text/#text-decoration) use it directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  text-decoration: none;
Don't use the text-decoration selector [Bootstrap has a class for text-decoration](https://getbootstrap.com/docs/4.4/utilities/text/#text-decoration) use it directly in your HTML file

2020-01-31 04:47 UTC, euqueme commented on main.css
> +  overflow: scroll;
Don't use overflow selector [Bootstrap has a class for overflow](https://getbootstrap.com/docs/4.4/utilities/overflow/) use it directly in your HTML file

2020-02-02 10:09 UTC, Kyle-Law commented on main.css
> +  display: flex;
Solved

2020-02-02 11:26 UTC, Kyle-Law commented on main.css
> +  font-weight: 600;
Solved

2020-02-02 11:26 UTC, Kyle-Law commented on main.css
> +  font-weight: 800;
solved

2020-02-02 11:26 UTC, Kyle-Law commented on main.css
> +  font-weight: 700;
solved

2020-02-02 11:29 UTC, Kyle-Law commented on main.css
> +  text-decoration: none;
solved

2020-02-02 11:29 UTC, Kyle-Law commented on main.css
> +  text-decoration: none;
solved

2020-02-02 11:31 UTC, Kyle-Law commented on main.css
> +  overflow: scroll;
solved

2020-02-02 11:33 UTC, Kyle-Law commented on main.css
> +  font-weight: 600;
solved

2020-02-02 15:33 UTC, Kyle-Law commented
Thank @euqueme  for your details review! Your suggestions have been implemented as listed below:

- Gray separator has been added between navbar children with `border-right`
- The missing sections of U.S., World, Business, Tech & Science, Culture, and Sports have been added
- NEWSLETTER red title has been added
- Header responsiveness on smaller screen fixed
- 'TOP STORY' is now the first article on a smaller screen with `order:-1;`
- The whole articles occupied 95% of the page width across screen sizes.
- FEATURE STORIES, TOP STORY, AND OPINION sections display at the same row on lg-screen size.
- Editor's Pick has 4 articles per row at the lg-screen size.
- `font-weight`,`text-decoration:none;`,`overflow:scroll;`,`margin & padding`,`text-align:center;`,`align-items & justify-content` CSS properties have been replaced with their respective bootstrap classes.

README.md has been updated with the latest live-link. Looking forward to another code review by TSEs :)

2020-02-02 16:40 UTC, mosesogwo requested changes
### Hi @Kyle-Law:clap:. Thank you for being receptive to reviews:heart:. Let us now take care of the following:

1. On small screens, in the **Opinion** section, let us reduce the margin between the image and the text.
![image](https://user-images.githubusercontent.com/46611870/73611252-36a51200-45e0-11ea-901e-65bf490d52ea.png)

2. Alignment of items on small screens in the **More Stories** section is **image on the left, text to the right,** Not text below image. The same applies for the **Latest News** section.

**Yours:**

![image](https://user-images.githubusercontent.com/46611870/73611300-ed08f700-45e0-11ea-80b8-3cde08506e62.png)

**Original:**

![image](https://user-images.githubusercontent.com/46611870/73611325-348f8300-45e1-11ea-9879-d56dae5aae20.png)


3. On small screens, the **More Stories** section comes before Culture and Travel. So we should have this order: **Top Story -> More Stories -> Culture & Travel,** not Top Story -> Culture & Travel -> More Stories.

4. On small screens, your **More Stories** column has an independent scroll from the page scroll, so not all content in the section is displayed until scrolled. That scroll shouldn't be there.

5. In the **Culture** section, one image is missing.
![image](https://user-images.githubusercontent.com/46611870/73611472-71a84500-45e2-11ea-9a10-522ec00bc7c7.png)

6. The background color of the footer section should be the same with that of the main section.

_**Kindly make these changes and submit another code review request**_

**Good luck:smile:**

**Status: Changes requested.**

2020-02-02 18:45 UTC, Kyle-Law commented
Thank @mosesogwo for reviewing my project! Your suggestions have been implemented as listed below:

1. The opinion section margin reduced on smaller screens.
2. Alignment of more stories section fix from left to right on small screens
3. Articles sequences fixed by setting the middle section `d-flex; flex-column`, then align its children with `order`.
4. Overflow removed on small screens.
5. 5th culture image restored.
6. Footer background-color added.

The latest live link is updated. Looking forward to another review by TSEs :)

2020-02-02 18:57 UTC, nikasulo requested changes
# Under Review By Tolulope Olusakin(TSE)
You have done a remarkable job! Just a few little issues with the UI. Give me a few minutes and I will give you full feedback.

2020-02-02 19:06 UTC, Oluwadamilareolusakin commented
# This is fantastic work @Kyle-Law 
You have come a really long way and your project has come together nicely! :rocket:. Please consider the few things I have commented about below :handshake: 

#### [OPTIONAL] Padding
You have done great with your responsiveness and the UI in general, however, if you look closely, there is a little bit of padding between your page and the edges of the browser on all screen sizes. This padding is cumulatively hurting your UI. Consider saying goodbye to it.

#### Menu
I must say, you have done nicely, however, you have it in you to take it a bit further! Please consider
the images I have attached below, showing your navigation bar on mobile and the navbar on the original site, you may notice that your buttons aren't responding as best as they can to the screen size. Consider making a few adjustments and it will tie it all together
![screenshot](https://thumbs2.imgbox.com/97/72/lYBOt1LJ_t.png)
![screenshot](https://thumbs2.imgbox.com/1d/12/JEXnLUxB_t.png)

#### Unresponsive section
Please consider the image I have attached below for the 'subscribe section' just below the section on top stories and the likes. It breaks down on smaller screen sizes. Consider making adjustments so your project can shine like it deserves.
![screenshot](https://thumbs2.imgbox.com/4c/58/sPsWXo3X_t.png)

#### Live link
Please remember to update the live link in your project to point to the actual website. My go to resource for making live links is [Raw Githack](https://raw.githack.com) Please check it out, it's free and easy to use :+1:

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-03 05:03 UTC, Kyle-Law commented
Thank @Oluwadamilareolusakin for reviewing my project! Your recommendations have been implemented as listed below:

- Unnecessary paddings removed
- Header stays responsive all the way to 300px
- 'Sign Up for newsletter' responsiveness fixed
- Live-link updated.

Looking forward to another code review by TSEs :)

2020-02-03 05:42 UTC, fatymahmed approved these changes
## Hi @Kyle-Law,
### You have done a great job 🎉🎉
[OPTIONAL]
- I suggest that you align your _Sign up for our newsletter_ section to the center for the smaller screens. 
- No need to request for another code review after you make this change.
### It's a 👍🏾 from me!
## ✔️ Approved!

Good luck with your next projects.
 _Don't forget to submit your project completion form_

2020-02-03 05:52 UTC, Kyle-Law commented
Thank @fatymahmed for approving my project! Your suggestion has been implemented with `mx-auto` on the container :)

2020-02-03 05:54 UTC, merged